### ISSUE TITLE
Older Browser Support

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#11]
Splitting breaks in IE9 due to `dataset` usage (IE11+). I don't specifically want to support browsers _all_ the way back, but I would like for it to not cause issues.

Is it worth making a mini "dataset" polyfill?
```
function getData(el, data) {
  return el.dataset ? el.dataset[data] : el.getAttribute('data-' + data)
}
```

Or converting them all to `el.getAttribute`?

Or just adding a test that kills Splitting before it can even run on incapable browsers?

**Comment by notoriousb1t** [comment]
I converted them to getAttribute.  it is less code and unless there is something remarkably different in terms of performance, I don't know that it is worth it to do that.

I also added a test for .html() and discovered it was not working exactly as intended, so there are fixes for that as well

**Comment by shshaw** [comment]
Awesome. Thanks! I'll run a test on IE9 again; see if there are other issues.
