### ISSUE TITLE
In mixed content, whitespace is not being preserved after word split

### ISSUE THREAD

**Issue by notoriousb1t** [shshaw/Splitting#13]
Example

```html
<div class="skid" data-splitting="chars">
  ARE <a href="#">WE</a><br />GOOD?
</div>
```
https://codepen.io/shshaw/pen/b97ceab839601bf0a1ac395c41488ca8

The space next to ARE should be preserved but is not

**Comment by notoriousb1t** [comment]
Fixed in https://github.com/shshaw/Splitting/commit/971c9405bc390025598cd84d0ede49976e54b963 

I added a test for this case and modified utils/split-text.js to preserve up to one space on either size of a phrase

**Comment by shshaw** [comment]
Awesome work! Looks good from here.

**Comment by notoriousb1t** [comment]
Cool. I'll close this out.
