### ISSUE TITLE
Logo on landing page has incorrect href

### ISSUE THREAD

**Issue by szynszyliszys** [shshaw/Splitting#16]
On [https://splitting.js.org/](https://splitting.js.org/) the logo leads to `https://splitting.js.org/guide.md` instead of `https://splitting.js.org/guide.html`

**Comment by shshaw** [comment]
Great catch! Thanks for letting me know.

Apparently VuePress isn't automatically processing that link, so I've utilized some of their helper functions to get that done and it's working now!

Thanks!
