### ISSUE TITLE
Splitting.lines - first line off

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#21]
Some issues with `Splitting.lines` where this first paragraph's lines aren't indexed properly:
https://codepen.io/shshaw/pen/d1daa677417bff05db4419c31c212ae5

Not sure what the cause is.

**Comment by notoriousb1t** [comment]
The bug was in detectGrid.  The default sort was doing alphanumeric (despite the type being number).  So 48 was being sorted after 108 for instance.

**Comment by shshaw** [comment]
Ah. Makes sense. Good catch!

**Comment by shshaw** [comment]
Tested and working. Still an issue related to #18 where it's not detecting the line changes when attempting to re-index.
