### ISSUE TITLE
Splitting() in React's componentDidMount not working

### ISSUE THREAD

**Issue by onetwothreebutter** [shshaw/Splitting#30]
Hi, thank you guys for this great library! I'm trying to use it in a React/GastbyJS project with this code:
```
class WorkIveDonePage extends React.Component {
    componentDidMount() {
        Splitting();
    }

    render() {
        return (
            <div>
                <section className="work__banner">
                    <div className="work__page-width">
                        <h1 className="site__banner-heading" data-splitting>
```
  

and I get the following error:
![screen shot 2018-09-02 at 1 57 15 pm](https://user-images.githubusercontent.com/3291622/44959703-3fa82600-aeb8-11e8-88d8-7af53af90c78.png)
  
  

Does this look like a bug or something on my side?

**Comment by notoriousb1t** [comment]
React is translating data-splitting to data-splitting=“true”. If you set it to chars or an empty string it should work properly. We are looking at making the error reporting better for this.

**Comment by notoriousb1t** [comment]
Also we are tracking the error reporting in this issue: https://github.com/shshaw/Splitting/issues/27

**Comment by shshaw** [comment]
Yes, it's an issue with React's treatment of properties and how we're detecting the split to use. I would recommend a bit more specific targeting of the element to be split, perhaps using [React's Refs](https://reactjs.org/docs/refs-and-the-dom.html) and `Splitting({ target: this.myRef })` to prevent splits running/re-running outside of your component.

Let us know if you have any questions, @onetwothreebutter!
