### ISSUE TITLE
Lines are not being wrapped

### ISSUE THREAD

**Issue by Slgoetz** [shshaw/Splitting#35]
From the sound of the documentation when you split by lines it should wrap each line in a dom element
```
const results = Splitting({ 
         target:target, 
	by:'lines'
});
```

If that is not the case, is it possible to do that?

**Comment by shshaw** [comment]
The documentation should likely be clarified a bit more :-) 

The way it works now is by splitting the words ( equivalent to `Splitting({ by: 'words' })` ), then adds a `--line-index` variable to each `.word`. This setup was to lessen the impact on the DOM when lines needed to be recalculated on resize. If you have DOM elements for each line, you have to shuffle the child elements around on resize versus just updating the style property.

This has [come up before](https://github.com/shshaw/Splitting/issues/34#issuecomment-454754330). I'm not directly opposed to having line wrappers, but it definitely ups the complexity and impacts performance each time it runs; though would help performance of certain animations (animating `.line` elements versus all the `.word` elements)

Certainly open to feedback.

**Comment by notoriousb1t** [comment]
I think if this is added it should be behind an option. I personally like the line indexing instead of adding dom nodes, but I definitely understand the desire to have it split everything in the dom for a one-time split in certain cases.

**Comment by FrankM1** [comment]
I'm looking to have lines wrapped as well. This is a pretty common use case when animating text.

**Comment by tleifj** [comment]
Has anyone come up with a way to implement this? Looking for a solution as well!

**Comment by ParallelUniv3rse** [comment]
+1
