### ISSUE TITLE
Splitting API

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#4]
Currently, `Splitting.chars`, `Splitting.words`, etc read quite well as an API, but in terms of flexibility, it can be a little tough to do more custom splits.

For example, I needed to include whitespace in a char split, and this is as simple as I could implement that.
```js
Splitting('[data-splitting]')
  .map(function(s, i) {
    Splitting.index(s, "char", Splitting.split(s.el, 'char', ''));
  });
```
https://codepen.io/shshaw/pen/7d1bd8f2c49fc6d6b8a405afcdee021a

The way `Splitting.index` and `Splitting.split` work could use some retooling, but I think a simple API change could solve the core issue here.

```js
Splitting({ 
   target: String|Node|Element|SplittingInstance
   split: "chars"|"words"|"lines"|"children"|String|RegularExp|Function
   key: String
   return: "string"|"array"
});
```

With a shorthand available for default or user added split functions:
```js
Splitting(target, splitType /* "chars","words","lines", etc. */);
```

And for an even simpler setup...
```js
// <div data-splitting="chars"></div> 
// <div data-splitting="words"></div>
Splitting(); // Automatically targets each [data-splitting] element and applies the value in the data attribute or defaults to "chars"
```

With the new API, my original example could be simplified down to this:
```js
Splitting({
  target: '[data-splitting]',
  split: '',
  key: 'char'
});
```

Any thoughts @notoriousb1t?

**Comment by notoriousb1t** [comment]
I think the direction of Splitting({ /* ... */ }) is going to be more flexible for api changes and extensibility, so I agree this is a better direction.  I would recommend a few changes to the naming conventions for read-out-loud-ability.

```js
Splitting({ 
    targets: 'div', 
    on: 'chars', 
    returns: 'string' 
})
```

That would read out loud as "Splitting targets ____ on _____ and returns ____".  Being able to call ```Splitting()``` and have it read from data attributes would be fantastic.  I think that removes the barrier of entry for people that are nervous about using JavaScript, but are otherwise very capable with HTML and CSS>

My personal experience with supporting additional signatures like ```Splitting(target, splitType /* "chars","words","lines", etc. */);``` has not been positive.  It ultimately means that duplicate document must be drawn up and it provides a poor upgrade path from Splitting(target, splitType) to Splitting({ /* more complicated config */ }).  

I don't 100% understand the nuance between key and split in your examples. What is the difference?

**Comment by shshaw** [comment]
Split is what the text will be divided by (String, RegEx, function), with
convenient shortcuts for various uses (words, chars, children, lines)
key is what the CSS vars will be named by ( —char-index, —char-total, etc)

**Comment by notoriousb1t** [comment]
I see, so key is the variable prefix?  That makes sense.

**Comment by shshaw** [comment]
Exactly. If the user provides a function to split, then they give a key for
Splitting to apply the prefixed vars.

If they don’t provide the key and it’s not a plug-in/default function,
should it do default vars (—index —total) or no vars?

**Comment by notoriousb1t** [comment]
Because vars cascade downward, I think it would be safer to no assign --index, --total without a key.  Maybe use --splitting-index, --splitting-total?

**Comment by shshaw** [comment]
Yeah, that or `--split-index` + `--split-total`.

Also, `by` instead of `split` or `on`? 
```js
Splitting({
  target: ...,
  by: ...
});
```

**Comment by shshaw** [comment]
Say you want to pre-split for Vue/React or whatever instead of a selector/node. This is currently handled via `Splitting.fromString`.

In the new API, should we use a `string` property instead of `target`, or use a separate method, like `Splitting.string`?

```
Splitting({
  string: 'hello world',
  by: 'chars',
  return: 'string'
});
// returns '<span class="splitting" style="--word-total: 2; --char-total: 10;"><span class="word">...'
```


```
Splitting.fromString('hello world', 'chars');
// or

Splitting.fromString({
  target: 'hello world',
  by: 'chars',
  return: 'string'|'element'
});
```

**Comment by notoriousb1t** [comment]
Split by makes sense and wouldn't be mislead someone to think it is an event handler.  

I think it might make sense to use a separate option instead of a new signature.  The ```string: ''``` is on the right track.   I think using the word ```content``` might be a little clearer depending on the specifics. Can Spitting.fromString accept html content?

**Comment by shshaw** [comment]
From our recent discussion:

- Drop the `return` option
- Move the string splitting functionality out to something like `Splitting.innerHTML({...})` with the shortcut of `Splitting.innerHTML('my text', 'chars');`

**Comment by shshaw** [comment]
Regarding `Splitting.children` / custom user functions, an `options` parameter containing an array of arguments to pass to the `by` parsing function.

```
Splitting({
  target: '.parent',
  by: 'children', // maps to a function via the plugin api
  key: 'item',
  options: ['.child-selector'] // Array of arguments to pass to the custom function? 
});
```

So for plugin-like functionality in the API,
```
Splitting.add({
  name: 'children', // This would then be available in `Splitting({ by: 'children' })`
  key: 'child', // Default key 
  by: function(target, options) {
    // Function run for each `target`, which is guaranteed to be an `Element` at this point)
    return Array.prototype.slice.call( target.querySelectorAll(options[0]) , 0);
    // Function should always return an array of Elements that are then passed to a `Splitting.index` style function to apply the `--key-index` var to items and `--key-total` to the target
  }
});
```

**Comment by notoriousb1t** [comment]
I merged the test branch from before into master locally and then pushed that up to 1.0.0.  I also re-arranged the code for the new api and got the existing test cases to pass.  

We still need more tests to cover all the apis, but at the very least we have a working build I think for ```Splitting({ target: ..., by: ... })```

**Comment by notoriousb1t** [comment]
https://github.com/shshaw/Splitting/tree/1.0.0

**Comment by shshaw** [comment]
Solid. I'll look it over. Thanks 👍
