### ISSUE TITLE
Line not calculated correctly when using <strong> tag

### ISSUE THREAD

**Issue by spbuckle** [shshaw/Splitting#40]
I have a word that has a `<strong>` tag wrapped around it and even though that word is on the second line, it's `--line-index` is 0 (instead of the expected 1). All other words have the correct line index and `--line-total` is correct.

**Comment by notoriousb1t** [comment]
Can you provide an example on CodePen?

**Comment by spbuckle** [comment]
Hi @notoriousb1t, thanks for the quick reply. Your idea of making a pen for it actually helped me solve the issue for myself. I'll share the pen anyways : https://codepen.io/anon/pen/LKBmGY It was all down to the `<strong>` tag having `position; relative;` on it.

**Comment by notoriousb1t** [comment]
Great to know! Thanks for the update (sorry for the delay in responding)
