### ISSUE TITLE
splliting is not defined

### ISSUE THREAD

**Issue by shaktis110** [shshaw/Splitting#43]
i am trying to use spllitingjs in my ionic project but it always gives splliting not defined error . i have added the given cdn but getting  same error again and again.
any help ..

**Comment by shshaw** [comment]
Double check the spelling and capitalization. It should be `Splitting`

I’m not very familiar with Ionic so that may require a bit more setup to
get it working.

**Comment by shaktis110** [comment]
thanks for quick response ..
no i have added the cdn is index.html and the response code is also 200 but can't access the object Splitting .is there any workaround for that .. thanks
