### ISSUE TITLE
Difference between comment and function arguments

### ISSUE THREAD

**Issue by MBehtemam** [shshaw/Splitting#48]
I try to read the codes but in this file, I see some difference between function arguments and doc:

```js
/**
 * # Splitting.split
 * Split an element's textContent into individual elements
 * @param el {Node} Element to split
 * @param key {string}
 * @param splitOn {string}
 * @param includeSpace {boolean}
 * @returns {HTMLElement[]}
 */
```
and the function arguments :
https://github.com/shshaw/Splitting/blob/d4d0a9ed3143fb992cc93220eadf1be3a355f8dd/src/utils/split-text.js#L13

**Comment by shshaw** [comment]
Thanks for pointing that out! We'll get that adjusted.

**Comment by notoriousb1t** [comment]
I've gone through and updated the jsdocs for most of the internals. Thanks for bringing this to our attention :)

Fixed in https://github.com/shshaw/Splitting/commit/6a1657429fea6a6cbcf85f067b1b8bc32bde8c62
