### ISSUE TITLE
Splitting.grid

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#5]
Merge [SplittingImage](https://github.com/shshaw/SplittingImage) into Splitting with a `Splitting.grid` function. They're basically the same (create elements/divide element and apply CSS vars) and could use all the same core functions.

API could be along these lines:
```js
Splitting.grid({
  target: ...,
  rows: 1,
  cols: 1,
  image: 'auto' // finds first <img> and applies it as `background-image`
    false // no background image applied
    URL // image directly set as background-image
});
```

**Comment by notoriousb1t** [comment]
I've got this on my radar.  Once I get the 1.0.0 passing tests for the whole API, I think this shouldn't be a big deal to move over.

**Comment by shshaw** [comment]
Based on our latest discussion:

`Splitting({ by: 'grid' })` = make a grid ( `SplittingImage` functionality ).
`Splitting({ by: 'layout' })` = detect layout, apply CSS vars.

Behind the scenes for `layout`, we could actually generalize it and make it two splits of `rows` and `cols` that users can use, and then `lines` could utilize the same backend.

`'layout' = ['rows', 'cols']`
`'lines' = ['words', 'rows']`

Does that make sense? `rows` would loop through elements and compare the `offsetTop`, `cols` would loop through elements and compare `offsetLeft`.

It assumes a linear progression in the current setup. Might need to be abstracted a bit. Something like this may work:

```
var rows = {};
elementArray.some( el => {
  ( rows[el.offsetTop] || rows[el.offsetTop] = [] ).push(el);
});
// then create an array from the object, sorted by the keys to be indexed as the `--row` value.
```

**Comment by shshaw** [comment]
`layout` may not be able to be so abbreviated as `['rows', 'cols']`. I don’t know that those would cascade smoothly into each other with the way rows & cols return arrays of arrays. Still, internally it should be able to use both of those directly and/or simply call `Splitting({ target: el, by: 'rows' })` and `Splitting({ target: el, by: 'cols' })`.
