### ISSUE TITLE
Vuejs - import module document is not defined  

### ISSUE THREAD

**Issue by mirkosaugo** [shshaw/Splitting#53]
When i import the Splitting module in my component like this:

`import Splitting from "splitting"`

I have this error: "document is not defined"

Which is the correct way to import it?

Thnx in advance

**Comment by shshaw** [comment]
Are you using a static site generator like Nuxt?

Splitting currently has to be run in the browser, and static site generators preprocess components in Node to spit out the HTML. We're working on adding deeper support for React/Vue/etc. https://github.com/shshaw/Splitting/issues/28

**Comment by mirkosaugo** [comment]
> Are you using a static site generator like Nuxt?
> 
> Splitting currently has to be run in the browser, and static site generators preprocess components in Node to spit out the HTML. We're working on adding deeper support for React/Vue/etc. #28

@shshaw yes im using Nuxt! Thank u for ur fast reply

**Comment by shshaw** [comment]
No problem. See this comment here for a React example that checks for if window & document are available before running Splitting: https://github.com/shshaw/Splitting/issues/20#issuecomment-495244241
