### ISSUE TITLE
Splitting.js doesn't handle complex-scripts

### ISSUE THREAD

**Issue by kotpal** [shshaw/Splitting#58]
For example, కోటిపల్లి has 4 glyphs or graphemes కో టి ప ల్లి and hence shouldn't be rendered as:
![image](https://user-images.githubusercontent.com/7716123/86332088-da7e0280-bbfe-11ea-8e03-937c5b52b2ed.png)
which is what Spliting.js does.

**Comment by ste-vg** [comment]
This is now fixed in version 1.1.0

https://codepen.io/ste-vg/pen/JjqWbyO
