### ISSUE TITLE
Splitting lines are inconsistent

### ISSUE THREAD

**Issue by gitgudcameron** [shshaw/Splitting#62]
Having an issue where line splitting is inconsistent, sometimes splitting 3 lines instead of 4 for example after simply refreshing the page. This makes text animation sometimes reveal two lines at the one time because it's wrapping in the container. Hope this makes sense.

Here is my codepen example. If you refresh the page a few times you should be able to see the animation not working correctly.

https://codepen.io/cameronknight/full/wvMZoNN

(Loving Splitting by the way 👌)

**Comment by AdvantageAustralia** [comment]
I figured it out. Just needed to wrap the code after CSS load

```
window.addEventListener("load", function(){
    // ....
});
```

**Comment by gitgudcameron** [comment]
I figured it out. Just needed to wrap the code to load after CSS.

window.addEventListener("load", function(){
    // ....
});

**Comment by onedaybefore** [comment]
Hello! 
Can you tell me if there is an alternative way? I load scripts asynchronously and in this case this method does not help me. Do you know another solution for string transfer to be correct with asynchronous script loading?
