### ISSUE TITLE
Splitting Defaults & Plugins

### ISSUE THREAD

**Issue by shshaw** [shshaw/Splitting#7]
Based on our recent conversation, I wanted to split (hehe) this part out from the Splitting API change to more clearly articulate what we're going for.

Ideally, the plugins.js would be something as simple as this:

```js
export default {
  words: { 
    key: 'word',
    by: /\s/+
  },
  
  chars: { 
    key: 'char',
    by: ['words', /*/+] // An array runs multiple plugins
  },

  lines: { 
    key: 'line'
    by: ['words', function(){}],
  },

  children: {
     key: 'child',
     by: require('./plugins/children') // or inline `function(){}`
  },
...

}
```

Then internally, when `Splitting(el, 'words')` is called, it runs something like
```js
if ( plugins[by] ) {
  var key = plugins[by].key;
  var splitBy = plugins[by].by;
  return splitElement(els).map(function(s, i) {
      return s[name] ? s :  // If the element has already been split by this method, just return.
        index(s, key, 
          typeof splitBy == 'function' ? 
            splitBy(s.el, options) // If the split by value is a function, run it
            : split(s.el, key, splitBy) // Otherwise, use the internal splitter
        );
    });
```

New plugins / default plugins could be added via the Splitting.add function, taking basically the same values
```
Splitting.add('chars',{
  key: 'char',
  by: /*/
});
```

**Comment by shshaw** [comment]
> I think it might make sense that if the user wants to separate words then chars, that they have to provide `['words', 'chars']` because the premise of this is that splitting chars alone is a valid use case
> One reason I like that design too is that you can expand upon it 
> `by: ['paragraphs', 'word', 'chars']`
> or by word and then by the letter "e" if you like `['word', /e/i]`

**Comment by shshaw** [comment]
My only qualm with that is I expect the most common use case to be splitting chars by word, I just don’t want to make that difficult. If we can come up with a shortcut for it. Perhaps

```
{
   words: {}
   allChars: {},
   chars: {
     by: ['words', 'allChars']
   }
}
```

**Comment by notoriousb1t** [comment]
How would you feel about having that as the default behavior? 

```js
Splitting(el) 

// same as 

Splitting(el, ['words', 'chars'])

// same as

Splitting({
    target: el
})

// same as

Splitting({
    target: el,
    by: ['words', 'chars']
})
```
I think rather than having a separate type, this might be a good compromise that makes the most common use case easy while providing a non-recursive plugin structure.

**Comment by shshaw** [comment]
I'm open to that. Thinking may be worth distinguishing between all characters (including whitespace) versus just characters in a word (each whitespace separated chunk of text).

**Comment by shshaw** [comment]
If done right, doing `allChars` and `chars` shouldn't really add any weight.

**Comment by notoriousb1t** [comment]
You are right, allChars vs chars is a lot clearer and should be no trouble between them
