### ISSUE TITLE
Consider using TypeScript for 1.0.0

### ISSUE THREAD

**Issue by notoriousb1t** [shshaw/Splitting#8]
How would you feel about using TypeScript for this project @shshaw?  I use it for most of my projects to help me keep the API's straight.  I feel like users would get a better experience with type-ahead in their IDE's as a result.  By starting with non-strict settings, it should provide a lot without having to formally define the whole code-base off the bat.

**Comment by shshaw** [comment]
🤢
I don't like a lot of abstractions, but if it's helpful for the end product and doesn't balloon the file size then I'm not specifically opposed.

Can you give me a short example of what that'd look like with non-strict settings?

**Comment by notoriousb1t** [comment]
With permissive settings, type annotations are not required (but there are some particular spots where it is useful to add them).  Take this piece of code:

```js
function square(a) {
   return a * a;
}
```

By adding one type annotation, we can ensure that what is going in is a number and the typescript compiler infers a number is coming out:
```ts
function square(a: number) {
   return a * a;
}
```

A more complicated example ```$``` would require explicit annotations to make the best of TypeScript, but it isn't required:

```js
export function $(e, parent) {
    return !e || e.length == 0
        ? // null or empty string returns empty array
          []
        : e.nodeName
            ? // a single element is wrapped in an array
              [e]
            : // selector and NodeList are converted to Element[]
              [].slice.call(e[0].nodeName ? e : (parent || root).querySelectorAll(e));
}
```
And with some type annotations, we can enforce a few contraints on how this is used:

```ts
export type Target = string | Node | NodeList | Node[];

export function $(e: Target , parent: Element): Element[] {
    return !e || e.length == 0
        ? // null or empty string returns empty array
          []
        : e.nodeName
            ? // a single element is wrapped in an array
              [e]
            : // selector and NodeList are converted to Element[]
              [].slice.call(e[0].nodeName ? e : (parent || root).querySelectorAll(e));
}
```
As I have used it over the past 5 years, I have become a big believer in using less and less types.  I think outside of import/export through rollup, it would be better to stick to ES5 features to ensure the typescript import is more or less unchanged as it becomes JavaScript.

The biggest area that I think this will improve is options coming in and values going out of the public API.  This will make TypeScript users and VSCode autocomplete more intelligently and help use keep from accidentally breaking compatibility.

**Comment by notoriousb1t** [comment]
Let me clarify this:
> As I have used it over the past 5 years, I have become a big believer in using less and less types
I think it is important to let the TypeScript compiler infer whatever it can rather than strong-arming and explicitly typing everything.  It becomes noise if you are too explicit.

**Comment by notoriousb1t** [comment]
Actually... maybe we should wait until 1.0.0 is solid before we talk about changing the language.

**Comment by shshaw** [comment]
Yeah; I'd be more comfortable with that.
