### ISSUE TITLE
Async splitting js

### ISSUE THREAD

**Issue by kj21012** [shshaw/Splitting#96]
Is there any way to convert splitting js to work with web worker?

**Comment by notoriousb1t** [comment]
I don't think web workers provide a general way to interact with the DOM. I can't think of a way to make this work out of the box with web workers because it performs the split on elements in the DOM and inserts new nodes into the DOM.

**Comment by shshaw** [comment]
I'm not aware of any ways the WebWorkers can directly manipulate DOM, thought I suspect this falls under https://github.com/shshaw/Splitting/issues/20 a bit. If APIs are updated to allow for custom `createElement` functions (React, Svelte, something compatible with Web Workers), then that would allow flexibility in how it's implemented.
